name: build

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate google-services.json
        env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE_JSON | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/app/google-services.json

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Report Unit Test Result
        if: cancelled() != true
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'

      - name: Build with Gradle
        run: ./gradlew assembleDebug
