name: assign

on:
  pull_request:
    types: [ opened ]

permissions:
  pull-requests: write
  repository-projects: read

jobs:
  assign:
    name: assign yourself
    runs-on: ubuntu-latest
    steps:
      - name: echo user
        run: echo '${{ github.event.pull_request.user.login }}'
      - name: Set GitHub assignees
        env:
          GH_TOKEN: ${{ github.token }}
        if: github.event.pull_request.user.login == 'renovate[bot]'
        run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
