name: assign

on:
  pull_request:
    types: opened

permissions:
  pull-requests: write
  repository-projects: read

jobs:
  assign:
    name: assign yourself
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub assignees
        env:
          access_token: ${{ github.token }}
        run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}